import React, { useState } from 'react';
import { useQuery, keepPreviousData } from '@tanstack/react-query';
import { fetchContacts } from '../services/crm.service';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Search, Download, ChevronLeft, ChevronRight } from 'lucide-react';

export default function CRM() {
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState<string | undefined>();
  
  const { data, isLoading, isError } = useQuery<any>({
    queryKey: ['contacts', page, statusFilter],
    queryFn: () => fetchContacts(page, 10, statusFilter),
    placeholderData: keepPreviousData
  });

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'HOT': return <span className="bg-destructive/20 text-destructive text-xs px-2 py-1 rounded-full font-medium">HOT</span>;
      case 'WARM': return <span className="bg-amber-500/20 text-amber-500 text-xs px-2 py-1 rounded-full font-medium">WARM</span>;
      case 'COLD': return <span className="bg-primary/20 text-primary text-xs px-2 py-1 rounded-full font-medium">COLD</span>;
      default: return <span className="bg-secondary text-muted-foreground text-xs px-2 py-1 rounded-full font-medium">{status}</span>;
    }
  };

  return (
    <div className="animate-fade-in space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">CRM Contacts</h1>
          <p className="text-muted-foreground mt-1">Manage leads generated by your AI automations.</p>
        </div>
        <Button variant="outline" className="gap-2">
          <Download size={16} /> Export CSV
        </Button>
      </div>

      <div className="bg-card border border-border rounded-xl shadow-lg overflow-hidden">
        {/* Table Toolbar */}
        <div className="p-4 border-b border-border flex items-center justify-between bg-muted/5">
          <div className="relative w-72">
            <Search size={16} className="absolute left-3 top-3 text-muted-foreground" />
            <Input className="pl-9 bg-background" placeholder="Search by name or username..." />
          </div>
          
          <div className="flex gap-2">
            <select 
              className="h-10 rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              value={statusFilter || ''}
              onChange={(e) => { setStatusFilter(e.target.value || undefined); setPage(1); }}
            >
              <option value="">All Statuses</option>
              <option value="HOT">Hot Leads</option>
              <option value="WARM">Warm Leads</option>
              <option value="COLD">Cold Leads</option>
            </select>
          </div>
        </div>

        {/* Data Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-muted-foreground uppercase bg-secondary/50 border-b border-border">
              <tr>
                <th className="px-6 py-4 font-medium">Lead Name</th>
                <th className="px-6 py-4 font-medium">Platform</th>
                <th className="px-6 py-4 font-medium text-center">Score</th>
                <th className="px-6 py-4 font-medium text-center">Status</th>
                <th className="px-6 py-4 font-medium">Captured Date</th>
                <th className="px-6 py-4 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {isLoading ? (
                <tr><td colSpan={6} className="px-6 py-12 text-center text-muted-foreground animate-pulse">Loading leads...</td></tr>
              ) : isError ? (
                <tr><td colSpan={6} className="px-6 py-12 text-center text-destructive">Error loading contacts.</td></tr>
              ) : data?.contacts?.length === 0 ? (
                <tr><td colSpan={6} className="px-6 py-12 text-center text-muted-foreground">No leads found.</td></tr>
              ) : (
                data?.contacts?.map((contact: any) => (
                  <tr key={contact._id} className="hover:bg-secondary/30 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-primary to-accent flex items-center justify-center text-white font-bold text-xs">
                          {contact.username?.substring(0, 2).toUpperCase() || 'IG'}
                        </div>
                        <div>
                          <div className="font-medium text-foreground">{contact.name || contact.username}</div>
                          {contact.name && <div className="text-xs text-muted-foreground">@{contact.username}</div>}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-muted-foreground">Instagram</td>
                    <td className="px-6 py-4 text-center">
                      <span className="font-bold text-foreground">{contact.leadScore}</span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      {getStatusBadge(contact.status)}
                    </td>
                    <td className="px-6 py-4 text-muted-foreground">
                      {new Date(contact.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Button variant="ghost" size="sm">View</Button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination Footer */}
        <div className="p-4 border-t border-border flex items-center justify-between bg-muted/5">
          <span className="text-sm text-muted-foreground">
            Showing <span className="font-medium text-foreground">{data?.contacts?.length || 0}</span> of <span className="font-medium text-foreground">{data?.pagination?.total || 0}</span> leads
          </span>
          <div className="flex gap-2">
            <Button 
              variant="outline" 
              size="sm" 
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={page === 1 || isLoading}
            >
              <ChevronLeft size={16} />
            </Button>
            <Button 
              variant="outline" 
              size="sm" 
              onClick={() => setPage(p => p + 1)}
              disabled={!data?.pagination || page >= data.pagination.pages || isLoading}
            >
              <ChevronRight size={16} />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
